language: csharp
solution: solution-name.sln
install:
  - nuget restore Realist.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release solution-name.sln
  - mono ./testrunner/xunit.runners.2.0.0/tools/xunit.console.clr4.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll